### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by LIUkhan** [zhuty16/CIGCN#2]
To my understanding, I use the CIGCN's aggregation step as follow:
for hop in range(3):
      agg_embed = F.tanh(torch.mul(torch.sparse.mm(D{-0.5}AD{-0.5}, X) , self.w_list[hop]))
And lightGCN's aggregation step is implemented as follow:
for hop in range(3):
      agg_embed = torch.sparse.mm(D{-0.5}AD{-0.5}, X)
I think this is the only change between CIGCN and LightGCN.
I have read your paper and source code carefully, but the experiment results don't show any improvement but suffer degeneration. I only use user/item interactions without item/item interactions. But I don't think it's the reason causing such a degeneration under your paper's hypothesis.
Could you please answer my question and point out what I miss for your idea?

**Comment by zhuty16** [comment]
Thank you for your question. I think it should be:
agg_embed = F.tanh(torch.sparse.mm(D{-0.5}AD{-0.5}, X) * w),
where w is a 1xd vector.

**Comment by LIUkhan** [comment]
I'm sorry I have tried as your codes do but still suffering degeneration, btw, torch.mul is the same as * operator. 
self.w_list[hop] in my code is a [nhops, d] parameter list for each layer as your suggestion in the paper. Both *w or *w_list[hop] suffer degeneration for all metrics.

**Comment by zhuty16** [comment]
I think you can try to tune the l2 regularization for w_list[hop].
