### ISSUE TITLE
代码能正常运行，但是preprocess.py该文件代码问题很多

### ISSUE THREAD

**Issue by Tong198-Hu** [zhuty16/CIGCN#4]
preprocess.py该文件debug后，存在一些问题🙋

**Comment by zhuty16** [comment]
你好，可能是pandas版本问题，我使用以前版本的pandas运行没有出现bug。同时请您注意您的表达措辞，谢谢。

**Comment by Tong198-Hu** [comment]
首先，我为我的鲁莽道歉。我想问一下，您用的pandas是哪个版本，因为我在debug过程中确实遇到了一些问题🙋
